Action()
{

	web_set_user("{login}", lr_unmask("5f01d23a53acb6"), 
		"47.100.95.28:8079");

	web_add_auto_header("DNT", 
		"1");

	web_add_header("Upgrade-Insecure-Requests", 
		"1");

	web_url("47.100.95.28:8079", 
		"URL=http://47.100.95.28:8079/", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=", 
		"Snapshot=t109.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/css/fonts/fontawesome-webfont.woff?v=4.0.3", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgVxIIzI.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxK.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5fBBc4.woff2", ENDITEM, 
		"Url=/items/holy_1.jpg", ENDITEM, 
		"Url=/items/puma_2.jpeg", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4.woff2", ENDITEM, 
		"Url=/items/holy_2.jpg", ENDITEM, 
		"Url=/items/puma_1.jpeg", ENDITEM, 
		"Url=/items/colourful_socks.jpg", ENDITEM, 
		"Url=/items/weave1.jpg", ENDITEM, 
		LAST);

	web_set_sockets_option("SSL_VERSION", "AUTO");

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("footer.html", 
		"URL=http://47.100.95.28:8079/footer.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/", 
		"Snapshot=t110.inf", 
		"Mode=HTML", 
		LAST);

	web_url("catalogue", 
		"URL=http://47.100.95.28:8079/catalogue?size=5", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/", 
		"Snapshot=t111.inf", 
		"Mode=HTML", 
		LAST);

	web_url("navbar.html", 
		"URL=http://47.100.95.28:8079/navbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/", 
		"Snapshot=t112.inf", 
		"Mode=HTML", 
		LAST);

	web_revert_auto_header("X-Requested-With");

	web_url("topbar.html", 
		"URL=http://47.100.95.28:8079/topbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/", 
		"Snapshot=t113.inf", 
		"Mode=HTML", 
		LAST);

	web_set_sockets_option("INITIAL_AUTH", "BASIC");

	web_add_header("X-Requested-With", 
		"XMLHttpRequest");

	lr_start_transaction("login");

/*Correlation comment: Automatic rules - Do not change!  
Original value='xr94oZj3N7FN9xzYIEcC-zXQYf0Sgt0S' 
Name ='CorrelationParameter' 
Type ='Rule' 
AppName ='Generic Rules' 
RuleName ='AutoGeneratedRuleName'*/
	web_reg_save_param_regexp(
		"ParamName=CorrelationParameter",
		"RegExp=logged_in=(.*?);",
		"Ordinal=1",
		SEARCH_FILTERS,
		"Scope=Cookies",
		"RequestUrl=*/login*",
		LAST);

	web_url("login", 
		"URL=http://47.100.95.28:8079/login", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/", 
		"Snapshot=t114.inf", 
		"Mode=HTML", 
		LAST);

	web_add_cookie("md.sid=s%3A{CorrelationParameter}.5oaNPkR0r0cH4vlNHIC43Ae8kglrUAOlSzQcuxcn8YY; DOMAIN=47.100.95.28");

	lr_end_transaction("login", LR_AUTO);

	web_add_header("Upgrade-Insecure-Requests", 
		"1");

	web_url("47.100.95.28:8079_2", 
		"URL=http://47.100.95.28:8079/", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=", 
		"Snapshot=t115.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/items/weave2.jpg", ENDITEM, 
		"Url=/items/cross_2.jpeg", ENDITEM, 
		"Url=/items/cross_1.jpeg", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxK.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5fBBc4.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgVxIIzI.woff2", ENDITEM, 
		"Url=/css/fonts/fontawesome-webfont.woff?v=4.0.3", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4.woff2", ENDITEM, 
		"Url=/items/weave1.jpg", ENDITEM, 
		"Url=/items/holy_1.jpg", ENDITEM, 
		"Url=/items/holy_2.jpg", ENDITEM, 
		"Url=/items/puma_2.jpeg", ENDITEM, 
		LAST);

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("catalogue_2", 
		"URL=http://47.100.95.28:8079/catalogue?size=5", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/", 
		"Snapshot=t116.inf", 
		"Mode=HTML", 
		LAST);

	web_url("navbar.html_2", 
		"URL=http://47.100.95.28:8079/navbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/", 
		"Snapshot=t117.inf", 
		"Mode=HTML", 
		LAST);

	web_revert_auto_header("X-Requested-With");

	web_add_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("footer.html_2", 
		"URL=http://47.100.95.28:8079/footer.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/", 
		"Snapshot=t118.inf", 
		"Mode=HTML", 
		LAST);

	web_add_header("Upgrade-Insecure-Requests", 
		"1");

	web_link("Catalogue", 
		"Text=Catalogue", 
		"Snapshot=t119.inf", 
		EXTRARES, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxK.woff2", ENDITEM, 
		"Url=/css/fonts/fontawesome-webfont.woff?v=4.0.3", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4.woff2", ENDITEM, 
		"Url=/items/holy_1.jpg", ENDITEM, 
		"Url=/img/product1.jpg", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5fBBc4.woff2", ENDITEM, 
		"Url=/items/colourful_socks.jpg", ENDITEM, 
		"Url=/items/puma_2.jpeg", ENDITEM, 
		"Url=/items/WAT.jpg", ENDITEM, 
		"Url=/items/puma_1.jpeg", ENDITEM, 
		"Url=/items/weave2.jpg", ENDITEM, 
		"Url=/items/WAT2.jpg", ENDITEM, 
		"Url=/items/cross_1.jpeg", ENDITEM, 
		"Url=/items/holy_2.jpg", ENDITEM, 
		"Url=/items/weave1.jpg", ENDITEM, 
		"Url=/items/cross_2.jpeg", ENDITEM, 
		LAST);

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("topbar.html_2", 
		"URL=http://47.100.95.28:8079/topbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t120.inf", 
		"Mode=HTML", 
		LAST);

	web_url("size", 
		"URL=http://47.100.95.28:8079/catalogue/size?tags=", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t121.inf", 
		"Mode=HTML", 
		LAST);

	web_url("footer.html_3", 
		"URL=http://47.100.95.28:8079/footer.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t122.inf", 
		"Mode=HTML", 
		LAST);

	web_url("navbar.html_3", 
		"URL=http://47.100.95.28:8079/navbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t123.inf", 
		"Mode=HTML", 
		LAST);

	web_url("catalogue_3", 
		"URL=http://47.100.95.28:8079/catalogue?page=1&size=6&tags=", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t124.inf", 
		"Mode=HTML", 
		LAST);

	web_url("tags", 
		"URL=http://47.100.95.28:8079/tags", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t125.inf", 
		"Mode=HTML", 
		LAST);

	web_revert_auto_header("X-Requested-With");

	lr_start_transaction("add item");

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("xr94oZj3N7FN9xzYIEcC-zXQYf0Sgt0S",
		"URL=http://47.100.95.28:8079/customers/{CorrelationParameter}",
		"Resource=0",
		"Referer=http://47.100.95.28:8079/category.html",
		"Snapshot=t126.inf",
		"Mode=HTML",
		LAST);

	lr_end_transaction("add item", LR_AUTO);

	web_revert_auto_header("X-Requested-With");

	web_url("cart", 
		"URL=http://47.100.95.28:8079/cart", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t127.inf", 
		"Mode=HTML", 
		LAST);

	web_add_header("Origin", 
		"http://47.100.95.28:8079");

	web_add_header("X-Requested-With", 
		"XMLHttpRequest");

	web_custom_request("cart_2", 
		"URL=http://47.100.95.28:8079/cart", 
		"Method=POST", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t128.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=utf-8", 
		"Body={\"id\":\"510a0d7e-8e83-4193-b483-e27e09ddc34d\"}", 
		LAST);

	web_add_auto_header("Upgrade-Insecure-Requests", 
		"1");

	web_url("basket.html", 
		"URL=http://47.100.95.28:8079/basket.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t129.inf", 
		"Mode=HTML", 
		LAST);

	web_revert_auto_header("Upgrade-Insecure-Requests");

	web_link("Continue shopping", 
		"Text=Continue shopping", 
		"Snapshot=t130.inf", 
		EXTRARES, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxK.woff2", ENDITEM, 
		"Url=/css/fonts/fontawesome-webfont.woff?v=4.0.3", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4.woff2", ENDITEM, 
		"Url=/img/logo.png", ENDITEM, 
		"Url=/items/holy_1.jpg", ENDITEM, 
		"Url=/img/product1.jpg", ENDITEM, 
		"Url=/items/holy_2.jpg", ENDITEM, 
		"Url=/items/puma_1.jpeg", ENDITEM, 
		"Url=/items/colourful_socks.jpg", ENDITEM, 
		"Url=/items/puma_2.jpeg", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5fBBc4.woff2", ENDITEM, 
		"Url=/items/cross_2.jpeg", ENDITEM, 
		"Url=/items/weave1.jpg", ENDITEM, 
		"Url=/items/WAT.jpg", ENDITEM, 
		"Url=/items/weave2.jpg", ENDITEM, 
		"Url=/items/WAT2.jpg", ENDITEM, 
		"Url=/items/cross_1.jpeg", ENDITEM, 
		LAST);

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("topbar.html_3", 
		"URL=http://47.100.95.28:8079/topbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t131.inf", 
		"Mode=HTML", 
		LAST);

	web_url("navbar.html_4", 
		"URL=http://47.100.95.28:8079/navbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t132.inf", 
		"Mode=HTML", 
		LAST);

	web_url("catalogue_4", 
		"URL=http://47.100.95.28:8079/catalogue?page=1&size=6&tags=", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t133.inf", 
		"Mode=HTML", 
		LAST);

	web_url("tags_2", 
		"URL=http://47.100.95.28:8079/tags", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t134.inf", 
		"Mode=HTML", 
		LAST);

	web_url("size_2", 
		"URL=http://47.100.95.28:8079/catalogue/size?tags=", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t135.inf", 
		"Mode=HTML", 
		LAST);

	web_url("footer.html_4", 
		"URL=http://47.100.95.28:8079/footer.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t136.inf", 
		"Mode=HTML", 
		LAST);

	web_revert_auto_header("X-Requested-With");

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("xr94oZj3N7FN9xzYIEcC-zXQYf0Sgt0S_2",
		"URL=http://47.100.95.28:8079/customers/{CorrelationParameter}",
		"Resource=0",
		"Referer=http://47.100.95.28:8079/category.html",
		"Snapshot=t137.inf",
		"Mode=HTML",
		LAST);

	web_url("cart_3", 
		"URL=http://47.100.95.28:8079/cart", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t138.inf", 
		"Mode=HTML", 
		LAST);

	web_revert_auto_header("X-Requested-With");

	web_add_auto_header("Upgrade-Insecure-Requests", 
		"1");

	web_url("basket.html_2", 
		"URL=http://47.100.95.28:8079/basket.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t139.inf", 
		"Mode=HTML", 
		LAST);

	web_revert_auto_header("Upgrade-Insecure-Requests");

	web_link("Add", 
		"Text=Add", 
		"Ordinal=1", 
		"Snapshot=t140.inf", 
		EXTRARES, 
		"Url=/css/fonts/fontawesome-webfont.woff?v=4.0.3", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxK.woff2", ENDITEM, 
		"Url=/img/logo-small.png", ENDITEM, 
		"Url=/items/holy_1.jpg", ENDITEM, 
		"Url=/items/puma_1.jpeg", ENDITEM, 
		"Url=/items/holy_2.jpg", ENDITEM, 
		"Url=/items/puma_2.jpeg", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5fBBc4.woff2", ENDITEM, 
		"Url=/items/colourful_socks.jpg", ENDITEM, 
		LAST);

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("footer.html_5", 
		"URL=http://47.100.95.28:8079/footer.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t141.inf", 
		"Mode=HTML", 
		LAST);

	web_url("navbar.html_5", 
		"URL=http://47.100.95.28:8079/navbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t142.inf", 
		"Mode=HTML", 
		LAST);

	web_url("topbar.html_4", 
		"URL=http://47.100.95.28:8079/topbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t143.inf", 
		"Mode=HTML", 
		LAST);

	web_url("cart_4", 
		"URL=http://47.100.95.28:8079/cart", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t144.inf", 
		"Mode=HTML", 
		LAST);

	web_url("catalogue_5", 
		"URL=http://47.100.95.28:8079/catalogue?size=3", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t145.inf", 
		"Mode=HTML", 
		LAST);

	web_url("card", 
		"URL=http://47.100.95.28:8079/card", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t146.inf", 
		"Mode=HTML", 
		LAST);

	web_revert_auto_header("X-Requested-With");

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("address", 
		"URL=http://47.100.95.28:8079/address", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t147.inf", 
		"Mode=HTML", 
		LAST);

	web_url("cart_5", 
		"URL=http://47.100.95.28:8079/cart", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t148.inf", 
		"Mode=HTML", 
		LAST);

	web_url("xr94oZj3N7FN9xzYIEcC-zXQYf0Sgt0S_3",
		"URL=http://47.100.95.28:8079/customers/{CorrelationParameter}",
		"Resource=0",
		"Referer=http://47.100.95.28:8079/basket.html",
		"Snapshot=t149.inf",
		"Mode=HTML",
		LAST);

	web_url("510a0d7e-8e83-4193-b483-e27e09ddc34d", 
		"URL=http://47.100.95.28:8079/catalogue/510a0d7e-8e83-4193-b483-e27e09ddc34d", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t150.inf", 
		"Mode=HTML", 
		LAST);

	web_url("510a0d7e-8e83-4193-b483-e27e09ddc34d_2", 
		"URL=http://47.100.95.28:8079/catalogue/510a0d7e-8e83-4193-b483-e27e09ddc34d", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t151.inf", 
		"Mode=HTML", 
		LAST);

	lr_start_transaction("add number");

	web_add_header("Origin", 
		"http://47.100.95.28:8079");

	web_custom_request("update", 
		"URL=http://47.100.95.28:8079/cart/update", 
		"Method=POST", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t152.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=utf-8", 
		"Body={\"id\":\"510a0d7e-8e83-4193-b483-e27e09ddc34d\",\"quantity\":\"{number}\"}", 
		LAST);

	web_revert_auto_header("X-Requested-With");

	web_add_header("Upgrade-Insecure-Requests", 
		"1");

	lr_end_transaction("add number", LR_AUTO);

	web_url("basket.html_3", 
		"URL=http://47.100.95.28:8079/basket.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t153.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/css/fonts/fontawesome-webfont.woff?v=4.0.3", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxK.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4.woff2", ENDITEM, 
		"Url=/img/logo-small.png", ENDITEM, 
		"Url=/img/logo.png", ENDITEM, 
		"Url=/items/puma_2.jpeg", ENDITEM, 
		"Url=/items/puma_1.jpeg", ENDITEM, 
		"Url=/items/holy_2.jpg", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5fBBc4.woff2", ENDITEM, 
		"Url=/items/holy_1.jpg", ENDITEM, 
		"Url=/items/colourful_socks.jpg", ENDITEM, 
		LAST);

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("navbar.html_6", 
		"URL=http://47.100.95.28:8079/navbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t154.inf", 
		"Mode=HTML", 
		LAST);

	web_url("footer.html_6", 
		"URL=http://47.100.95.28:8079/footer.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t155.inf", 
		"Mode=HTML", 
		LAST);

	web_url("cart_6", 
		"URL=http://47.100.95.28:8079/cart", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t156.inf", 
		"Mode=HTML", 
		LAST);

	web_url("address_2", 
		"URL=http://47.100.95.28:8079/address", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t157.inf", 
		"Mode=HTML", 
		LAST);

	web_url("topbar.html_5", 
		"URL=http://47.100.95.28:8079/topbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t158.inf", 
		"Mode=HTML", 
		LAST);

	web_url("catalogue_6", 
		"URL=http://47.100.95.28:8079/catalogue?size=3", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t159.inf", 
		"Mode=HTML", 
		LAST);

	web_url("card_2", 
		"URL=http://47.100.95.28:8079/card", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t160.inf", 
		"Mode=HTML", 
		LAST);

	web_url("cart_7", 
		"URL=http://47.100.95.28:8079/cart", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t161.inf", 
		"Mode=HTML", 
		LAST);

	web_url("510a0d7e-8e83-4193-b483-e27e09ddc34d_3", 
		"URL=http://47.100.95.28:8079/catalogue/510a0d7e-8e83-4193-b483-e27e09ddc34d", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t162.inf", 
		"Mode=HTML", 
		LAST);

	web_url("xr94oZj3N7FN9xzYIEcC-zXQYf0Sgt0S_4",
		"URL=http://47.100.95.28:8079/customers/{CorrelationParameter}",
		"Resource=0",
		"Referer=http://47.100.95.28:8079/basket.html",
		"Snapshot=t163.inf",
		"Mode=HTML",
		LAST);

	web_url("510a0d7e-8e83-4193-b483-e27e09ddc34d_4", 
		"URL=http://47.100.95.28:8079/catalogue/510a0d7e-8e83-4193-b483-e27e09ddc34d", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t164.inf", 
		"Mode=HTML", 
		LAST);

	web_add_header("Origin", 
		"http://47.100.95.28:8079");
	
	lr_think_time(14);

	lr_start_transaction("add address");

	web_custom_request("addresses", 
		"URL=http://47.100.95.28:8079/addresses", 
		"Method=POST", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t165.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=utf-8", 
		"Body={address}", 
		LAST);

	web_revert_auto_header("X-Requested-With");

	web_add_header("Upgrade-Insecure-Requests", 
		"1");

	lr_end_transaction("add address", LR_AUTO);

	web_url("basket.html_4", 
		"URL=http://47.100.95.28:8079/basket.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t166.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/css/fonts/fontawesome-webfont.woff?v=4.0.3", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxK.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4.woff2", ENDITEM, 
		"Url=/items/puma_1.jpeg", ENDITEM, 
		"Url=/items/holy_1.jpg", ENDITEM, 
		"Url=/items/holy_2.jpg", ENDITEM, 
		"Url=/items/puma_2.jpeg", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5fBBc4.woff2", ENDITEM, 
		"Url=/items/colourful_socks.jpg", ENDITEM, 
		LAST);

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("topbar.html_6", 
		"URL=http://47.100.95.28:8079/topbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t167.inf", 
		"Mode=HTML", 
		LAST);

	web_url("cart_8", 
		"URL=http://47.100.95.28:8079/cart", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t168.inf", 
		"Mode=HTML", 
		LAST);

	web_url("footer.html_7", 
		"URL=http://47.100.95.28:8079/footer.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t169.inf", 
		"Mode=HTML", 
		LAST);

	web_url("navbar.html_7", 
		"URL=http://47.100.95.28:8079/navbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t170.inf", 
		"Mode=HTML", 
		LAST);

	web_url("address_3", 
		"URL=http://47.100.95.28:8079/address", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t171.inf", 
		"Mode=HTML", 
		LAST);

	web_url("card_3", 
		"URL=http://47.100.95.28:8079/card", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t172.inf", 
		"Mode=HTML", 
		LAST);

	web_url("catalogue_7", 
		"URL=http://47.100.95.28:8079/catalogue?size=3", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t173.inf", 
		"Mode=HTML", 
		LAST);

	web_url("xr94oZj3N7FN9xzYIEcC-zXQYf0Sgt0S_5",
		"URL=http://47.100.95.28:8079/customers/{CorrelationParameter}",
		"Resource=0",
		"Referer=http://47.100.95.28:8079/basket.html",
		"Snapshot=t174.inf",
		"Mode=HTML",
		LAST);

	web_revert_auto_header("X-Requested-With");

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("510a0d7e-8e83-4193-b483-e27e09ddc34d_5", 
		"URL=http://47.100.95.28:8079/catalogue/510a0d7e-8e83-4193-b483-e27e09ddc34d", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t175.inf", 
		"Mode=HTML", 
		LAST);

	web_url("cart_9", 
		"URL=http://47.100.95.28:8079/cart", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t176.inf", 
		"Mode=HTML", 
		LAST);

	web_url("510a0d7e-8e83-4193-b483-e27e09ddc34d_6", 
		"URL=http://47.100.95.28:8079/catalogue/510a0d7e-8e83-4193-b483-e27e09ddc34d", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t177.inf", 
		"Mode=HTML", 
		LAST);

	web_add_header("Origin", 
		"http://47.100.95.28:8079");
	
	lr_think_time(5);

	lr_start_transaction("add cards");
	
	web_custom_request("cards", 
		"URL=http://47.100.95.28:8079/cards", 
		"Method=POST", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t178.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=utf-8", 
		"Body={cards}", 
		LAST);

	web_revert_auto_header("X-Requested-With");

	web_add_header("Upgrade-Insecure-Requests", 
		"1");

	lr_end_transaction("add cards", LR_AUTO);

	web_url("basket.html_5", 
		"URL=http://47.100.95.28:8079/basket.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/category.html", 
		"Snapshot=t179.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxK.woff2", ENDITEM, 
		"Url=/css/fonts/fontawesome-webfont.woff?v=4.0.3", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4.woff2", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4.woff2", ENDITEM, 
		"Url=/items/holy_1.jpg", ENDITEM, 
		"Url=/items/holy_2.jpg", ENDITEM, 
		"Url=/items/puma_2.jpeg", ENDITEM, 
		"Url=https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5fBBc4.woff2", ENDITEM, 
		"Url=/items/colourful_socks.jpg", ENDITEM, 
		"Url=/items/puma_1.jpeg", ENDITEM, 
		LAST);

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("card_4", 
		"URL=http://47.100.95.28:8079/card", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t180.inf", 
		"Mode=HTML", 
		LAST);

	web_url("cart_10", 
		"URL=http://47.100.95.28:8079/cart", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t181.inf", 
		"Mode=HTML", 
		LAST);

	web_url("address_4", 
		"URL=http://47.100.95.28:8079/address", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t182.inf", 
		"Mode=HTML", 
		LAST);

	web_url("topbar.html_7", 
		"URL=http://47.100.95.28:8079/topbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t183.inf", 
		"Mode=HTML", 
		LAST);

	web_url("catalogue_8", 
		"URL=http://47.100.95.28:8079/catalogue?size=3", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t184.inf", 
		"Mode=HTML", 
		LAST);

	web_url("footer.html_8", 
		"URL=http://47.100.95.28:8079/footer.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t185.inf", 
		"Mode=HTML", 
		LAST);

	web_url("navbar.html_8", 
		"URL=http://47.100.95.28:8079/navbar.html", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t186.inf", 
		"Mode=HTML", 
		LAST);

	web_url("510a0d7e-8e83-4193-b483-e27e09ddc34d_7", 
		"URL=http://47.100.95.28:8079/catalogue/510a0d7e-8e83-4193-b483-e27e09ddc34d", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t187.inf", 
		"Mode=HTML", 
		LAST);

	web_revert_auto_header("X-Requested-With");

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("xr94oZj3N7FN9xzYIEcC-zXQYf0Sgt0S_6",
		"URL=http://47.100.95.28:8079/customers/{CorrelationParameter}",
		"Resource=0",
		"Referer=http://47.100.95.28:8079/basket.html",
		"Snapshot=t188.inf",
		"Mode=HTML",
		LAST);

	lr_start_transaction("place order");

	web_revert_auto_header("X-Requested-With");

	web_url("cart_11", 
		"URL=http://47.100.95.28:8079/cart", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t189.inf", 
		"Mode=HTML", 
		LAST);

	web_add_auto_header("X-Requested-With", 
		"XMLHttpRequest");

	web_url("510a0d7e-8e83-4193-b483-e27e09ddc34d_8", 
		"URL=http://47.100.95.28:8079/catalogue/510a0d7e-8e83-4193-b483-e27e09ddc34d", 
		"Resource=0", 
		"Referer=http://47.100.95.28:8079/basket.html", 
		"Snapshot=t190.inf", 
		"Mode=HTML", 
		LAST);

	web_add_auto_header("Origin", 
		"http://47.100.95.28:8079");

	lr_end_transaction("place order", LR_AUTO);

	return 0;
}